package com.ykx.dao;

import com.ykx.entity.OrderItem;
import com.ykx.entity.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int deleteByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    OrderItem selectByPrimaryKey(Integer orderitemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByPrimaryKey(OrderItem record);
}