package com.ykx.dao;

import com.ykx.entity.Prorder;
import com.ykx.entity.ProrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    long countByExample(ProrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int deleteByExample(ProrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int insert(Prorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int insertSelective(Prorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    List<Prorder> selectByExample(ProrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    Prorder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Prorder record, @Param("example") ProrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByExample(@Param("record") Prorder record, @Param("example") ProrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByPrimaryKeySelective(Prorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prorder
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    int updateByPrimaryKey(Prorder record);
}