package com.ykx.entity;

import java.math.BigDecimal;

public class Cart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.cart_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    private Integer cartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.user_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.product_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.pro_number
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    private Integer proNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.sum
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    private BigDecimal sum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.cart_id
     *
     * @return the value of cart.cart_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.cart_id
     *
     * @param cartId the value for cart.cart_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.user_id
     *
     * @return the value of cart.user_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.user_id
     *
     * @param userId the value for cart.user_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.product_id
     *
     * @return the value of cart.product_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.product_id
     *
     * @param productId the value for cart.product_id
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.pro_number
     *
     * @return the value of cart.pro_number
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public Integer getProNumber() {
        return proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.pro_number
     *
     * @param proNumber the value for cart.pro_number
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public void setProNumber(Integer proNumber) {
        this.proNumber = proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.sum
     *
     * @return the value of cart.sum
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public BigDecimal getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.sum
     *
     * @param sum the value for cart.sum
     *
     * @mbg.generated Sun Oct 20 11:27:32 CST 2019
     */
    public void setSum(BigDecimal sum) {
        this.sum = sum;
    }
}