package com.ykx.entity;

import java.math.BigDecimal;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_name
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private String proName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_price
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private BigDecimal proPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_img
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private String proImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_msg
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    private String proMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_name
     *
     * @return the value of product.pro_name
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_name
     *
     * @param proName the value for product.pro_name
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_price
     *
     * @return the value of product.pro_price
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public BigDecimal getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_price
     *
     * @param proPrice the value for product.pro_price
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setProPrice(BigDecimal proPrice) {
        this.proPrice = proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_img
     *
     * @return the value of product.pro_img
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public String getProImg() {
        return proImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_img
     *
     * @param proImg the value for product.pro_img
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setProImg(String proImg) {
        this.proImg = proImg == null ? null : proImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_msg
     *
     * @return the value of product.pro_msg
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public String getProMsg() {
        return proMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_msg
     *
     * @param proMsg the value for product.pro_msg
     *
     * @mbg.generated Fri Oct 18 19:14:56 CST 2019
     */
    public void setProMsg(String proMsg) {
        this.proMsg = proMsg == null ? null : proMsg.trim();
    }
}