package com.ykx.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Prorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.order_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.user_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.orderCode
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.order_sum
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private BigDecimal orderSum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.order_number
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Integer orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.address
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.mobile
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.createDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.post
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.receiver
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.payDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Date paydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.deliverDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Date deliverdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.confirmDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private Date confirmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.status
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prorder.real_name
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    private String realName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.order_id
     *
     * @return the value of prorder.order_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.order_id
     *
     * @param orderId the value for prorder.order_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.user_id
     *
     * @return the value of prorder.user_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.user_id
     *
     * @param userId the value for prorder.user_id
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.orderCode
     *
     * @return the value of prorder.orderCode
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.orderCode
     *
     * @param ordercode the value for prorder.orderCode
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.order_sum
     *
     * @return the value of prorder.order_sum
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public BigDecimal getOrderSum() {
        return orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.order_sum
     *
     * @param orderSum the value for prorder.order_sum
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setOrderSum(BigDecimal orderSum) {
        this.orderSum = orderSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.order_number
     *
     * @return the value of prorder.order_number
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.order_number
     *
     * @param orderNumber the value for prorder.order_number
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.address
     *
     * @return the value of prorder.address
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.address
     *
     * @param address the value for prorder.address
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.mobile
     *
     * @return the value of prorder.mobile
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.mobile
     *
     * @param mobile the value for prorder.mobile
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.createDate
     *
     * @return the value of prorder.createDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.createDate
     *
     * @param createdate the value for prorder.createDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.post
     *
     * @return the value of prorder.post
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.post
     *
     * @param post the value for prorder.post
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.receiver
     *
     * @return the value of prorder.receiver
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.receiver
     *
     * @param receiver the value for prorder.receiver
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.payDate
     *
     * @return the value of prorder.payDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.payDate
     *
     * @param paydate the value for prorder.payDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.deliverDate
     *
     * @return the value of prorder.deliverDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Date getDeliverdate() {
        return deliverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.deliverDate
     *
     * @param deliverdate the value for prorder.deliverDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setDeliverdate(Date deliverdate) {
        this.deliverdate = deliverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.confirmDate
     *
     * @return the value of prorder.confirmDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public Date getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.confirmDate
     *
     * @param confirmdate the value for prorder.confirmDate
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.status
     *
     * @return the value of prorder.status
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.status
     *
     * @param status the value for prorder.status
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prorder.real_name
     *
     * @return the value of prorder.real_name
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prorder.real_name
     *
     * @param realName the value for prorder.real_name
     *
     * @mbg.generated Mon Oct 21 14:01:17 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}